### PR TITLE
Generic exception message to catch-all exception

### LINKED ISSUE #92: AuthorizationMiddleware catch-all leaks internal exception messages in HTTP response
## Summary

`AuthorizationMiddleware::process()` has a catch-all for `\Exception` (line 77–80 of `src/AuthorizationMiddleware.php`) that passes the raw `$exception->getMessage()` into an `OAuthServerException`, which then renders it in the HTTP response body as `error_description`. This can expose internal infrastructure details (e.g. database hostnames, IP addresses, ports, file paths) to end users.

## Relevant code

```php
} catch (BaseException $exception) {
    $response = $this->responseFactory->createResponse();
    return (new OAuthServerException($exception->getMessage(), 0, 'unknown_error', 500))
        ->generateHttpResponse($response);
}
```

For example, if the underlying database is unreachable, the exception message may contain something like:

```
SQLSTATE[HY000] [2002] Connection refused (tcp://db-host.internal:3306)
```

This ends up in the JSON response:

```json
{
  "error": "unknown_error",
  "error_description": "SQLSTATE[HY000] [2002] Connection refused (tcp://db-host.internal:3306)",
  "message": "SQLSTATE[HY000] [2002] Connection refused (tcp://db-host.internal:3306)"
}
```

## Comparison with TokenEndpointHandler

`TokenEndpointHandler::handle()` only catches `OAuthServerException` and does not have a catch-all for general exceptions. This means it does not have the same information disclosure issue — uncaught exceptions there would bubble up to the application's error handler, which typically sanitizes output.

## Suggested fix

Replace `$exception->getMessage()` with a generic message:

```php
} catch (BaseException $exception) {
    $response = $this->responseFactory->createResponse();
    return (new OAuthServerException('An internal error occurred', 0, 'unknown_error', 500))
        ->generateHttpResponse($response);
}
```

Additionally, it would be useful to accept an optional `Psr\Log\LoggerInterface` so the original exception can be logged rather than silently discarded:

```php
public function __construct(
    AuthorizationServer $server,
    $responseFactory,
    ?LoggerInterface $logger = null
) {
    // ...
    $this->logger = $logger;
}
```

```php
} catch (BaseException $exception) {
    $this->logger?->error('Authorization request error', ['exception' => $exception]);
    $response = $this->responseFactory->createResponse();
    return (new OAuthServerException('An internal error occurred', 0, 'unknown_error', 500))
        ->generateHttpResponse($response);
}
```

## Impact

This is an information disclosure issue that affects any deployment where `AuthorizationMiddleware` is used and an unexpected exception (e.g. database connection failure, misconfiguration) occurs during `validateAuthorizationRequest()`.

## Version

Observed in `2.12.0`, confirmed still present on `main`.

### PR DESCRIPTION
**Pull request by pinclau**
|    Q          |   A
|-------------- | ------
| Documentation | no
| Bugfix        | yes
| BC Break      | no
| New Feature   | yes
| RFC           | no
| QA            | no

### Description
This PR addresses #92 issued by @marcguyer and implements his "suggested fix". I added a test for the new `LoggerInterface`

### CODE REVIEW

**Comment by arhimede** [comment]
@mezzio/tsc-reviewers 
With this PR , we can release the version 3 of this library

File: src/AuthorizationMiddleware.php [hunk 1]
```diff
@@ -41,10 +42,12 @@ class AuthorizationMiddleware implements MiddlewareInterface
     /** @var ResponseFactoryInterface */
     protected $responseFactory;
 
+    protected ?LoggerInterface $logger;
+
     /**
      * @param (callable():ResponseInterface)|ResponseFactoryInterface $responseFactory
      */
-    public function __construct(AuthorizationServer $server, $responseFactory)
+    public function __construct(AuthorizationServer $server, $responseFactory, ?LoggerInterface $logger = null)
```
Comment (froschdesign) [inline src/AuthorizationMiddleware.php:50]: We have here a typical problem: nobody knows about it.
There is a simple rule: _what is not documented does not exist._

Comment (froschdesign) [reply src/AuthorizationMiddleware.php:50]: The related factory should also be extended:

https://github.com/mezzio/mezzio-authentication-oauth2/blob/2733daeb5087f9fd6529ea2f3689a54b6aa3594a/src/AuthorizationMiddlewareFactory.php#L16-L20

The `Psr\Container\ContainerInterface` defines a `has` method which can be used here.

**Review by froschdesign — CHANGES_REQUESTED** [review]

File: src/AuthorizationMiddleware.php (hunk 1 above)
Comment (pinclau) [reply src/AuthorizationMiddleware.php:50]: @froschdesign i made changes to the related factory
What should we do about the documentation?

**Comment by arhimede** [comment]
Thnanks @pinclau

**Comment by froschdesign** [comment]
@arhimede 
What is the point of the release if the new features are not documented? Correct, that release is useless!

And other tasks and problems have not been solved. Examples:

https://github.com/mezzio/mezzio-authentication-oauth2/blob/a631d533ec5bb764b1a4e6f8c9f4d83e4a6aacf1/src/AuthorizationHandler.php#L26-L28

https://github.com/mezzio/mezzio-authentication-oauth2/blob/a631d533ec5bb764b1a4e6f8c9f4d83e4a6aacf1/src/ConfigProvider.php#L66-L81

---

I understand that things need to be finished quickly or that features need to be made available quickly, but the quality of a release shouldn’t suffer as a result.

**Comment by arhimede** [comment]
> I understand that things need to be finished quickly or that features need to be made available quickly, but the quality of a release shouldn’t suffer as a result.

Correct. 

But right now, the cycle PR->review->fix->review->fix is way too long. 
We need to find a a middle ground here.

**Comment by gsteel** [comment]
I might add that this release shipped with `callable` response generators that should have been factored out since the availability of the HTTP factories PSR.

I agree with @froschdesign that quality takes precedence, not development velocity.

**Comment by arhimede** [comment]
> I might add that this release shipped with `callable` response generators that should have been factored out since the availability of the HTTP factories PSR.
> 
> I agree with @froschdesign that quality takes precedence, not development velocity.

Where is the fine line between perfection and utility ?

This release solve an issue which is at least 2 years old, and it is quite an important one.

We need to show to the community that 
- we are still delivering 
- we still make important releases 
- we keep updating old packages that are `active`
- we keep solving real problems
- Laminas packages was and still are an option for enterprise platforms
- etc.

Users faces real life problems, and high quality need to be balanced with a reasonable velocity. 
Bugs can be fixed, refactoring here and there can be done in a minor release.

**Comment by froschdesign** [comment]
> we still make important releases

Not this one, because what's new?

> …and it is quite an important one.

**But which is not documented…**
It is a shame all that effort goes to waste if it isn’t communicated.

The release notes are also not meaningful, on the contrary, they even contain an entry for a closed pull request that is not relevant to the version.
What was the problem with waiting another day or two? I had this pull request on my list and wanted to offer feedback and help with the documentation.

I am not saying that everything needs to be overhauled, but the new version – and especially a major version – should make sense. That is the point, nothing more.

**Comment by gsteel** [comment]
I acknowledge and appreciate your drive to keep stuff moving forward, but _every_ major release I've ever made has gone to the TSC for an approval vote before publication - this gives everyone the chance to scrutinise (or not) what's getting changed before it ships.

I thought this was a requirement, but it's not [listed here](https://github.com/laminas/technical-steering-committee/blob/main/processes/VOTING.md#decisions-requiring-a-vote).

We could probably do with some clarification on that at the next meeting 👍

**Comment by arhimede** [comment]
> > we still make important releases
> 
> Not this one, because what's new?

It is noted here: https://github.com/mezzio/mezzio-authentication-oauth2/releases
**Upgrade league/oauth2-server from v8 to v9**

> > …and it is quite an important one.
> 
> **But which is not documented…** It is a shame all that effort goes to waste if it isn’t communicated.
> 
> The release notes are also not meaningful, on the contrary, they even contain an entry for a closed pull request that is not relevant to the version. What was the problem with waiting another day or two? I had this pull request on my list and wanted to offer feedback and help with the documentation.

Indeed I missed the  documentation structure, we will fix it with versions.

> I am not saying that everything needs to be overhauled, but the new version – and especially a major version – should make sense. That is the point, nothing more.

we are working at `laminas-session` next major version for more then 1 year.
It is too much , in my opinion....

**Comment by arhimede** [comment]
> I acknowledge and appreciate your drive to keep stuff moving forward, but _every_ major release I've ever made has gone to the TSC for an approval vote before publication - this gives everyone the chance to scrutinise (or not) what's getting changed before it ships.
> 
> I thought this was a requirement, but it's not [listed here](https://github.com/laminas/technical-steering-committee/blob/main/processes/VOTING.md#decisions-requiring-a-vote).
> 
> We could probably do with some clarification on that at the next meeting 👍

The process is too slow. 
We are calling for contributors, and only to have their PR's lingering for months ?

I am sorry, my bad. 
Indeed i am aware that it is an unwriten rule to ask for a vote in TSC, and i neglected this part.

But things need to move forward ...

**Comment by froschdesign** [comment]
> we are working at `laminas-session` next major version for more then 1 year.
> It is too much , in my opinion....

I agree with you, but it would be even more disastrous if there were no documentation of the new features and changes. 😜 

> The process is too slow.
> We are calling for contributors, and only to have their PR's lingering for months ?

That may be true, but my job takes priority, so I can’t keep an eye on everything. There are 31 members in total; perhaps that’s where you should start.
